[package]
name = "rusty-scheme"
version = "0.0.3"
authors = ["bryal <96.bryal@gmail.com>"]
repository = "https://github.com/bryal/rusty-scheme"
license = "MIT"

[dependencies]
getopts = "*"
bitflags = "*"
