[package]
name = "kvasir-lang"
version = "0.1.1"
authors = ["bryal <96.bryal@gmail.com>"]
repository = "https://github.com/bryal/kvasir-lang"
license = "GPLv3"
build = "build.rs"

[dependencies]
getopts = "*"
bitflags = "*"
lazy_static = "*"
term = "*"
llvm-alt = "*"
llvm-sys = "*"
itertools = "*"