[package]
name = "kvaser-lang"
version = "0.1"
authors = ["bryal <96.bryal@gmail.com>"]
repository = "https://github.com/bryal/kvaser-lang"
license = "GPLv3"
build = "build.rs"

[dependencies]
getopts = "*"
bitflags = "*"
lazy_static = "*"
term = "*"
llvm-sys = "0.2.1"
libc = "*"